### ISSUE TITLE
error: field expected struct or pointer to struct

### ISSUE THREAD

**Issue by deltaskelta** [neelance/graphql-go#158]
I took apart the star wars example and tried to make my own example from it and it seems to be throwing an error that I can't understand...

```
panic: field "Add": expected struct or pointer to struct, got *string
	returned by (*cmd.Resolver).HelloAnd

goroutine 1 [running]:
github.com/neelance/graphql-go.MustParseSchema(0x1423626, 0x16d, 0x13a4900, 0x1647140, 0x0, 0x0, 0x0, 0xc420090e68)
	/Users/Jeff/go/src/github.com/neelance/graphql-go/graphql.go:55 +0xb1
github.com/deltaskelta/interviews/server/cmd.init.0()
	/Users/Jeff/go/src/github.com/deltaskelta/interviews/server/cmd/root.go:24 +0x7e
github.com/deltaskelta/interviews/server/cmd.init()
	<autogenerated>:1 +0x6c
main.init()
	<autogenerated>:1 +0x44
exit status 2
```

Any idea what is causing this? Here is the code. 
```
package cmd

var Schema = `
	schema {
		query: Query
		mutation: Mutation
	}

	# The query type, represents all of the entry points into the graph
	type Query {
		hello(): Response
	}

	type Mutation {
		helloAnd(add: ResponseInput!): Response
	}

	# a standard response
	type Response {
		name: String!
	}

	# input to pass to the helloAnd mutation
	input ResponseInput {
		add: String!
	}

`

// Resolver is the root resolver, which must take care of the Query and mutation
type Resolver struct{}

// Hello reolves the query method hello which returns a Response
func (r *Resolver) Hello() *Response {
	return &Response{"hello"}
}

type Response struct {
	name string
}

func (s *Response) Name() string {
	return s.name
}

// TODO
// why isn't this working?

// how can I do a join?

// how can I simply stack the resolvers to work with related fields? are m2m relationships
// different?

// what are edges and nodes? why are they in queries sometimes?

// HelloAnd resolves the query method helloAnd
type ResponseInput struct {
	Add *string
}

func (r *Resolver) HelloAnd(add *ResponseInput) *Response {
	// create it, add it to the db and then return a feed to the resolver
	return &Response{"world"}
}
```

**Comment by darh** [comment]
try with `struct { Add string }`

ie: if there is an `!` there should not be an `*` :)

**Comment by deltaskelta** [comment]
I changed it and I still get the error with this...

```
func (r *Resolver) HelloAnd(args struct{ Add string }) *Response {
	// create it, add it to the db and then return a feed to the resolver
	return &Response{"world"}
}

```

**Comment by deltaskelta** [comment]
I see my error now, it was that the args passed to the mutation should always be in a struct...which I had defined to take another struct as input instead of just a string.

I seem to have a hard time relating the schema from a string into code in my head. @darh are you aware of any codegen tools for this? It would be super cool if I could write the schema and then generate all the resolver stubs to just fill in

**Comment by darh** [comment]
Nope, sorry. I'm doing everything manually. It's really not that time-consuming after a while when you have some base code to c/p from. But I wouldn't mind having a tool for it :)

**Comment by deltaskelta** [comment]
ok, I don't have a big picture in my head to make a tool yet, but I am working on a simple example with pets and owners that uses a real sqlite db with gorm. Would you be interested in reviewing/adding that example when it is finished?

**Comment by darh** [comment]
Sure. Keep in mind that I have like 3-week experience with this lib.

**Comment by deltaskelta** [comment]
oh, lol I thought you were a maintainer, lol. Ill link the PR here when it is finished. @neelance what do you think?

**Comment by salmana1** [comment]
@deltaskelta

we have hard forked an existing codgen tool and actively working on it. Please take a look at: [graphql-gen-go](https://github.com/DealTap/graphql-gen-go). Feedback and PRs are welcome :)
