### ISSUE TITLE
JSON scalar

### ISSUE THREAD

**Issue by bsr203** [neelance/graphql-go#22]
Hi,

I am trying to receive JSON input, and define a scalar type like

```
var JSON = &graphql.ScalarConfig{
	ReflectType: reflect.TypeOf(json.RawMessage{}),
	CoerceInput: func(input interface{}) (interface{}, error) {
		switch input := input.(type) {
		case string:
			j := json.RawMessage([]byte(input))
			return &j, nil
		default:
			return nil, fmt.Errorf("wrong type")
		}
	},
}
```

When I use it, gets the following error

```

2016/11/17 20:23:14 graphql: graphql: panic occured: reflect.Set: value of type *string is not assignable to type *json.RawMessage
goroutine 54 [running]:
github.com/neelance/graphql-go/internal/exec.(*request).handlePanic(0xc4202b4600)
	/Users/bsr/.../external/src/github.com/neelance/graphql-go/internal/exec/exec.go:393 +0x123
panic(0x57a380, 0xc420345ef0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
reflect.Value.assignTo(0x5629e0, 0xc420345ee0, 0x16, 0x66308e, 0xb, 0x5b1d00, 0x0, 0x16, 0x5629e0, 0xc420345ee0)
	/usr/local/go/src/reflect/value.go:2163 +0x35c
reflect.Value.Set(0x5b1d00, 0xc4202b4bf0, 0x196, 0x5629e0, 0xc420345ee0, 0x16)
	/usr/local/go/src/reflect/value.go:1333 +0xa4
github.com/neelance/graphql-go/internal/exec.(*structPacker).pack(0xc42046e640, 0x5ab660, 0xc4204dfb38, 0x57a380, 0xc420198580, 0x9349e0)
INFO     2016-11-18 01:23:14,549 module.py:788] default: "POST /graphql HTTP/1.1" 200 138
	/Users/bsr/.../external/src/github.com/neelance/graphql-go/internal/exec/exec.go:751 +0x2b3
```

how should I change the scalar definition.

thanks.

**Comment by nicksrandall** [comment]
At first glance it looks like you have to add a case for *string and not just string. With graphql, if you choose something to be nullable, you'll need to support the case for it to be a pointer.

**Comment by bsr203** [comment]
thanks @nicksrandall 
I gave it a try again, and it is working. I probably used string as the arg in the resolver instead of json.RawMessage. I had to avoid one indirection. Final code.

```
var JSON = &graphql.ScalarConfig{
	ReflectType: reflect.TypeOf(json.RawMessage{}),
	CoerceInput: func(input interface{}) (interface{}, error) {
		switch input := input.(type) {
		case string:
			j := json.RawMessage([]byte(input))
			return j, nil
		default:
			return nil, fmt.Errorf("wrong type")
		}
	},
}```

thanks again.
