### ISSUE TITLE
panic on missing input variable

### ISSUE THREAD

**Issue by bsr203** [neelance/graphql-go#26]
It would be great to detect the mistake during initial parse than at run time.
```
type Mutation {
  updateHuman(ClientMutationId: String!, input: UpdateHumanInput!): updateHumanPayload
}

mutation M($in: UpdateHumanInput!) {
  updateHuman(clientMutationId: "1",input: $in ) {
    ...
  }
}
```
above gives the panic, as `clientMutationId` should be `ClientMutationId`

below works

```
mutation M($in: UpdateHumanInput!) {
  updateHuman(ClientMutationId: "1",input: $in ) {
    ...
  }
}

```

stack

```
2016/11/18 18:04:46 graphql: graphql: panic occured: runtime error: invalid memory address or nil pointer dereference
goroutine 36 [running]:
github.com/neelance/graphql-go/internal/exec.(*request).handlePanic(0xc4201a18c0)
	/Users/bsr/.../external/src/github.com/neelance/graphql-go/internal/exec/exec.go:392 +0x123
panic(0x5b1760, 0xc420012060)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/neelance/graphql-go/internal/exec.(*fieldExec).execField2(0xc4204513b0, 0x934400, 0xc4201c5ad0, 0xc4201a18c0, 0xc4201a17c0, 0x5c0960, 0x984ae8, 0x16, 0x937a20, 0xc420472c80, ...)
	/Users/bsr/.../external/src/github.com/neelance/graphql-go/internal/exec/exec.go:664 +0x1f9
github.com/neelance/graphql-go/internal/exec.(*fieldExec).execField(0xc4204513b0, 0x934400, 0xc4201c59b0, 0xc4201a18c0, 0xc4201a17c0, 0x5c0960, 0x984ae8, 0x16, 0xc4201872c0)
	/Users/bsr/.../external/src/github.com/neelance/graphql-go/internal/exec/exec.go:640 +0x3b2
github.com/neelance/graphql-go/internal/exec.(*objectExec).execSelectionSet.func2()
	/Users/bsr/.../external/src/github.com/neelance/graphql-go/internal/exec/exec.go:573 +0x3f4
github.com/neelance/graphql-go/internal/exec.(*objectExec).execSelectionSet.func1(0xc42019d540)
	/Users/bsr/.../external/src/github.com/neelance/graphql-go/internal/exec/exec.go:524 +0xc0
INFO     2016-11-18 23:04:46,763 module.py:788] default: "POST /graphql HTTP/1.1" 200 125
github.com/neelance/graphql-go/internal/exec.(*objectExec).execSelectionSet(0xc4204568a0, 0x934400, 0xc4201c59b0, 0xc4201a18c0, 0xc420187260, 0x5c0960, 0x984ae8, 0x16, 0xc4201872c0, 0x54701)

```

**Comment by neelance** [comment]
This is probably related to #5. You want an error on parse time of the query, correct?

**Comment by bsr203** [comment]
yes. not too critical but nice to have. thanks.

**Comment by bsr203** [comment]
thanks.. it doesn't happen anymore.
