### ISSUE TITLE
Graphiql is broken.

### ISSUE THREAD

**Issue by nicksrandall** [neelance/graphql-go#65]
If you view graphiql in the starwars example of of this repo, you'll see that you are greeted with a confusing error. This was introduced when support for deprecated fields was added. 

I'm investigating the root cause of the error.

**Comment by tonyghita** [comment]
Is this what you're seeing?
```
GraphQLError
    at syntaxError (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.9.3/graphiql.min.js:11:31952)
    at expect (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.9.3/graphiql.min.js:13:19595)
    at parseValue (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.9.3/graphiql.min.js:13:8637)
    at m (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.9.3/graphiql.min.js:15:30463)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.9.3/graphiql.min.js:12:29066
    at Array.reduce (native)
    at keyValMap (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.9.3/graphiql.min.js:12:29030)
    at y (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.9.3/graphiql.min.js:15:30330)
    at v (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.9.3/graphiql.min.js:15:31065)
    at Array.map (native)
```

**Comment by nicksrandall** [comment]
yup

**Comment by tonyghita** [comment]
I'm seeing this in a different project that uses GraphiQL... I'm specifying
```
  <script src="https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.9.3/graphiql.min.js"></script>
```
 as part of my page... I wonder if some bad code got pushed to that CDN.

**Comment by nicksrandall** [comment]
I thought that at first too... but the star wars example uses a old version and it is still broken: 
```
GraphQLError
    at syntaxError (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.7.8/graphiql.js:17406:15)
    at expect (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.7.8/graphiql.js:20819:32)
    at parseValue (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.7.8/graphiql.js:19940:3)
    at buildInputValue (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.7.8/graphiql.js:24640:118)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.7.8/graphiql.js:19062:31
    at Array.reduce (native)
    at keyValMap (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.7.8/graphiql.js:19061:15)
    at buildInputValueDefMap (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.7.8/graphiql.js:24633:36)
    at buildDirective (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.7.8/graphiql.js:24657:13)
    at Array.map (native)
```

I also tried `unpkg.com` cdn and got same result

**Comment by tonyghita** [comment]
I can reproduce with other CDNs as well... I was going to try an older version but no luck.

**Comment by nicksrandall** [comment]
My first guess is that the error is here: https://github.com/neelance/graphql-go/blob/498fe3961c3058c45f5ad90b1212a48adfbba266/internal/schema/meta.go#L41-47

**Comment by tonyghita** [comment]
Ahhh interesting... I did pull in the latest commits today.

**Comment by nicksrandall** [comment]
I push a work around... see #66
