### ISSUE TITLE
Panic on exec.go

### ISSUE THREAD

**Issue by robmadden** [neelance/graphql-go#68]
Hi, I'm getting a panic in `exec.go` when I am running the introspection query (I've tried both cURL and GraphQL IDE) and finding it very difficult to debug. Any help/suggestions appreciated. Below you'll find my stack trace. I omitted the full paths of some of my directories for sake of privacy.

Here's the introspection query I'm trying:

```graphql
query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }   
    }
}
```

Here's my schema:

```
package campaigns

// Schema is the schema for campaigns
var Schema = `
  schema {
    query:    Query
    mutation: Mutation
  }

  type Query {
  }

  type Mutation {
    CreateCampaign(campaign: CampaignInput!): Campaign
  }

  type Campaign {
    uuid: ID!
    userUUID: ID!
    packageUUID: ID!
  }

  input CampaignInput {
    userUUID: ID!
    packageUUID: ID!
  }
`
```

Here's the stack trace of the panic I'm seeing:

```
goroutine 8 [running]:
...vendor/github.com/neelance/graphql-go/internal/exec.(*request).handlePanic(0xc420013fc0)
	go/src/github.com/spbk/worf/vendor/github.com/neelance/graphql-go/internal/exec/exec.go:310 +0x123
panic(0x4cc180, 0xc4200180a0)
	/usr/local/Cellar/go/1.7.4_2/libexec/src/runtime/panic.go:458 +0x243
.../vendor/github.com/neelance/graphql-go/internal/exec.ExecuteRequest.func1(0xc420013fc0, 0x0, 0x0, 0x7f89e0, 0xc420311e30, 0xc420012980, 0xc420012440, 0x213b00, 0x0, 0x0)
	go/src/github.com/spbk/worf/vendor/github.com/neelance/graphql-go/internal/exec/exec.go:340 +0x68
vendor/github.com/neelance/graphql-go/internal/exec.ExecuteRequest(0x7f89e0, 0xc420311e30, 0xc420012440, 0xc4203ab670, 0x0, 0x0, 0x0, 0x7faf80, 0x835c68, 0x9ad348, ...)
	go/src/github.com/spbk/worf/vendor/github.com/neelance/graphql-go/internal/exec/exec.go:341 +0x26a
vendor/github.com/neelance/graphql-go.(*Schema).Exec(0xc4203ab190, 0x7f89e0, 0xc4203d1aa0, 0xc4201d0c00, 0x5a6, 0x0, 0x0, 0x0, 0x0)
	go/src/github.com/spbk/worf/vendor/github.com/neelance/graphql-go/graphql.go:121 +0x3cd
github.com/spbk/worf/api.(*graphQLHandler).ServeHTTP(0xc42002c120, 0x7f81e0, 0xc4204204e0, 0xc4200d6780)
	go/src/github.com/spbk/worf/api/api.go:60 +0x1a8
github.com/spbk/worf/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203a4320, 0x7f81e0, 0xc4204204e0, 0xc4200d6780)
	go/src/github.com/spbk/worf/vendor/github.com/gorilla/mux/mux.go:114 +0x10d
net/http.serverHandler.ServeHTTP(0xc420380280, 0x7f81e0, 0xc4204204e0, 0xc4200d65a0)
	/usr/local/Cellar/go/1.7.4_2/libexec/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420380300, 0x7f8920, 0xc420012780)
	/usr/local/Cellar/go/1.7.4_2/libexec/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.7.4_2/libexec/src/net/http/server.go:2293 +0x44d

```

**Comment by robmadden** [comment]
Note, as soon as I remove mutations from my schema, the introspection query works.

**Comment by robmadden** [comment]
I figured it out. My schema didn't have a query type defined and it appears the library can't handle that case (perhaps this is a constraint in the spec).

**Comment by getaaron** [comment]
@robmadden Please open an issue suggesting more descriptive/helpful error messages in this case.

**Comment by robmadden** [comment]
@getaaron no.
