### ISSUE TITLE
Panic occurs when a query is submitted which does not access any subfields.

### ISSUE THREAD

**Issue by thedodd** [neelance/graphql-go#69]
When making a query as such: `query='{__schema { types { name }}}'`, you get the expected response:
```js
{
    "data": {
        "__schema": {
            "types": [
                {
                    "name": "Boolean"
                },
                ...
            ]
        }
    }
}
```

Same with a query like: `query='{__schema {}}'`, you get the expected response:
```js
{
    "data": {
        "__schema": { }
    }
}
```

However, if you leave off the `{}` after `__schema` like so: `query='{__schema}'`, you get a runtime panic:
```go-stacktrace
graphql: panic occurred: runtime error: invalid memory address or nil pointer dereference
 goroutine 109 [running]:
 <vendor>/github.com/neelance/graphql-go/internal/exec.(*request).handlePanic(0xc420276d40)
 	<vendor>/github.com/neelance/graphql-go/internal/exec/exec.go:341 +0x123
 panic(0x98cae0, 0xd779a0)
 	/usr/local/go/src/runtime/panic.go:489 +0x2cf
 <vendor>/github.com/neelance/graphql-go/internal/exec.(*objectExec).execSelectionSet(0xc420142f30, 0xd51820, 0xc42027b6e0, 0xc420276d40, 0x0, 0x9c6500, 0xc4202a02d0, 0x16, 0xc420)
 	<vendor>/github.com/neelance/graphql-go/internal/exec/exec.go:475 +0x64
 <vendor>/github.com/neelance/graphql-go/internal/exec.(*objectExec).exec(0xc420142f30, 0xd51820, 0xc42027b6e0, 0xc420276d40, 0x0, 0x9c6500, 0xc4202a02d0, 0x16, 0x0, 0xc4202affb8
 	<vendor>/github.com/neelance/graphql-go/internal/exec/exec.go:469 +0x250
 <vendor>/github.com/neelance/graphql-go/internal/exec.introspectSchema(0xd51820, 0xc42027b6e0, 0xc420276d40, 0x0, 0x1, 0xa6d501)
 	<vendor>/github.com/neelance/graphql-go/internal/exec/introspection.go:42 +0xe3
 <vendor>/github.com/neelance/graphql-go/internal/exec.(*objectExec).execField(0xc4202585a0, 0xd51820, 0xc42027b6e0, 0xc420276d40, 0xc420276cc0, 0x98e4c0, 0xc42000f480, 0x16, 0xc
 	<vendor>/github.com/neelance/graphql-go/internal/exec/exec.go:552 +0xbec
 <vendor>/github.com/neelance/graphql-go/internal/exec.(*objectExec).execSelectionSet.func2()
 	<vendor>/github.com/neelance/graphql-go/internal/exec/exec.go:498 +0x72
 <vendor>/github.com/neelance/graphql-go/internal/exec.(*objectExec).execSelectionSet.func1.1(0xc4202755f0, 0xc420276d40, 0xc4202a6870)
 	<vendor>/github.com/neelance/graphql-go/internal/exec/exec.go:487 +0x77
 created by <vendor>/github.com/neelance/graphql-go/internal/exec.(*objectExec).execSelectionSet.func1
 	<vendor>/github.com/neelance/graphql-go/internal/exec/exec.go:488 +0xce
```

I will be hacking on resolving this issue, as I need it to work properly for my API.

**Comment by neelance** [comment]
This and several other query validation rules have been implemented now. Please tell me if you see any other such issues.
